version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgresdb1
    restart: always
    ports:
      - '5430:5430'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db1