name: Deploy to Server

on:
  push:
    branches:
      - main # Adjust branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: process.env.NEXT_PUBLIC_SERVER_HOST
          username: process.env.NEXT_PUBLIC_SERVER_USER
          key: process.env.NEXT_PUBLIC_SERVER_PASSWORD
          script: |
            cd /code/rama-backend/
            git pull

            # Any other commands needed to restart your project
